version: '3'

services:
  web:
    build: ./IBManagerWeb
    image: ibweb:latest
    command: python -m ibweb.main
    ports:
      - 5000:80
    volumes:
      - ./IBManagerWeb:/IBManagerWeb
    links:
      - db
      - downloader
      - tone-calc
      - ibgw
    depends_on:
      - downloader
      - tone-calc
      - db
      - mongolog
      - ibgw
  downloader:
    build: ./Downloaders/DataDownloader/EarningsTranscript
    image: downloader:latest
    ports:
      - 5001:80
    links:
      - db
    depends_on:
      - mongolog
  tone-calc:
    build: ./Transformers/ToneCalculator
    image: tone-calc:latest
    volumes:
      - ./Transformers/ToneCalculator:/tone
    ports:
      - 5002:80
    links:
      - db
    depends_on:
      - mongolog
  db:
    image: mongo
    ports:
      - 27017:27017
  ibgw:
    build: ./ibgateway/ib-docker
    image: ibgw:latest
    ports:
    - "4003:4003"
    - "5900:5900"
    volumes:
      - ./ibgateway/ib-docker/IBController.ini:/root/IBController/IBController.ini
      - ./ibgateway/ib-docker/jts.ini:/root/Jts/jts.ini
    environment:
      # - TZ=Australia/Adelaide
      - VNC_PASSWORD=password
      - TWS_MAJOR_VRSN=960
      - IBC_INI=/root/IBController/IBController.ini
      - TRADING_MODE=
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - TWSUSERID=ahafb502
      - TWSPASSWORD=proba12
      - FIXUSERID=
      - FIXPASSWORD=
      - JAVA_PATH=
      - APP=GATEWAY
  mongolog:
    build: ./mongolog
    image: mongolog:latest
    command: 'true'