version: '3'

services:
  product-service:
    build: ./product
    image: product-service:latest
    volumes:
      - ./product:/prod
    ports:
      - 5001:80
  website:
    build: ./website
    image: website:latest
    volumes:
      - ./website:/web
    ports:
      - 5000:80
    depends_on:
      - product-service